/*
 * EXT_INT_Config.h
 *
 * Created: 4/17/2021 10:51:05 PM
 *  Author: Moustafa Moubarak
 */ 


#ifndef EXT_INT_CONFIG_H_
#define EXT_INT_CONFIG_H_

#define		GLOBAL_INTERRUPT				GLOBAL_INTERRUPT_ENABLE

#define		EXTERNAL_INT0_TRIGGER			TRIGGER_RISING
#define		EXTERNAL_INT1_TRIGGER			TRIGGER_RISING
#define		EXTERNAL_INT2_TRIGGER			TRIGGER_RISING

#endif /* EXT_INT_CONFIG_H_ */