/*
 * ADC_MCAL.c
 *
 * Created: 5/3/2021 10:22:48 PM
 *  Author: Moustafa Moubarak
 */ 

#include "ADC_MCAL.h"

void ADC_Init(void)
{
	#if		ADC_VOLTAGE_REF			==			ADC_VREF_AVCC
	SET_BIT(ADMUX, 6);
	CLR_BIT(ADMUX, 7);
	
	#elif	ADC_VOLTAGE_REF			==			ADC_VREF_AREF
	CLR_BIT(ADMUX, 6);
	CLR_BIT(ADMUX, 7);
	
	#elif	ADC_VOLTAGE_REF			==			ADC_VREF_INTERNAL
	SET_BIT(ADMUX, 6);
	SET_BIT(ADMUX, 7);
	#endif
	
	
	#if		ADC_ADJUST				==			ADC_RIGHT_ADJUST
	CLR_BIT(ADMUX, 5);
	
	#elif	ADC_ADJUST				==			ADC_LEFT_ADJUST
	SET_BIT(ADMUX, 5);
	#endif
	
	
	#if		ADC_CHANNEL				==			ADC_CHANNEL_1
	SET_BIT(ADMUX, 0);
	
	#elif	ADC_CHANNEL				==			ADC_CHANNEL_2
	SET_BIT(ADMUX, 1);
	
	#elif	ADC_CHANNEL				==			ADC_CHANNEL_3
	SET_BIT(ADMUX, 1);
	SET_BIT(ADMUX, 2);

	#elif	ADC_CHANNEL				==			ADC_CHANNEL_4
	SET_BIT(ADMUX, 2);
	
	#elif	ADC_CHANNEL				==			ADC_CHANNEL_5
	SET_BIT(ADMUX, 0);
	SET_BIT(ADMUX, 2);
	
	#elif	ADC_CHANNEL				==			ADC_CHANNEL_6
	SET_BIT(ADMUX, 1);
	SET_BIT(ADMUX, 2);
	
	#elif	ADC_CHANNEL				==			ADC_CHANNEL_7
	SET_BIT(ADMUX, 0);
	SET_BIT(ADMUX, 1);
	SET_BIT(ADMUX, 2);

	#endif
	
	#if		ADC_CONVERSION_TRIGGER	==			ADC_AUTO_TRIGGER
	SET_BIT(ADCSRA, 5);
	
	#endif
	
	#if		ADC_PRESCALER			==			ADC_PRESCALER_2
	SET_BIT(ADCSRA, 0);
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_4
	SET_BIT(ADCSRA, 1);
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_8
	SET_BIT(ADCSRA, 0);
	SET_BIT(ADCSRA, 1);
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_16
	SET_BIT(ADCSRA, 2);
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_32
	SET_BIT(ADCSRA, 2);
	SET_BIT(ADCSRA, 0);	
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_64
	SET_BIT(ADCSRA, 2);
	SET_BIT(ADCSRA, 1);
	
	#elif		ADC_PRESCALER		==			ADC_PRESCALER_128
	SET_BIT(ADCSRA, 2);
	SET_BIT(ADCSRA, 1);
	SET_BIT(ADCSRA, 0);
	
	#endif
	
	#if			ADC_INTERRUPT_STATUS	==			ADC_INERRUPT_ENABLE
	SET_BIT(ADCSRA, 3);
	
	#elif		ADC_INTERRUPT_STATUS	==			ADC_INERRUPT_ENABLE
	CLR_BIT(ADCSRA, 3);
	#endif
	
	//Enable the ADC
	SET_BIT(ADCSRA, 7);
}

void ADC_Read(uint16* value)
{
	SET_BIT(ADCSRA, 1);
	while(GET_BIT(ADCSRA, 4)==0);
	*value = ADC_FINAL;
}
